spring.application.name=interview-portal
jwt.secret=A9x#kL92!pQw3Z@rT8uV6yB1cD4eF7gE
spring.datasource.url=jdbc:postgresql://localhost:5432/interview_portal
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true